name: "Release dev-container feature"
on: workflow_dispatch

jobs:
  update-docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      -
        name: "Checkout"
        uses: actions/checkout@v3
      -
        name: "Generate docs"
        uses: devcontainers/action@v1
        with:
          base-path-to-features: "./features"
          generate-docs: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      -
        name: "Commit docs if changed"
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update docs"
          file_pattern: "features/**/README.md"

  release:
    runs-on: ubuntu-latest
    needs: update-docs
    permissions:
      contents: write
      packages: write
    steps:
      -
        name: "Checkout"
        uses: actions/checkout@v3
      -
        name: "Build and release"
        uses: devcontainers/action@v1
        with:
          base-path-to-features: "./features"
          publish-features: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}